### ISSUE TITLE
MailChimp's CSS inliner is stripping my inpage styles which I want to have to responsive columns.

### ISSUE THREAD

**Issue by jitendravyas** [darylldoyle/Gulp-Email-Creator#4]

**Comment by darylldoyle** [comment]
Hmm, do you have an example of the code that I can play with anywhere? I can't see why it'd strip it when it's inline unless it's overwriting it

**Comment by jitendravyas** [comment]
When I create responsive email we use CSS Media quesries which can't be used as inline so we keep it inside ``<head><style>..here...</style></head>``

And in your gulp workflow ``<style></style>`` is being removed

**Comment by jitendravyas** [comment]
You can test with below code

`````````````
<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
			.hello {font-size:58px;}
        </style>
    </head>
    <body>
       
        <p>Hello world! This is HTML5 Boilerplate.</p>

    </body>
</html>
```````````````````````````````

In final output  below will be removed
````````     
<style>
.hello {font-size:58px;}
</style>
`````````````

**Comment by jitendravyas** [comment]
Thanks but I'm getting this error now
````````````````
module.js:338
    throw err;
          ^
Error: Cannot find module 'mailchimp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jitendravyas/projects/email/node_modules/gulp-mc-inliner/lib/index.js:1:82)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```````````````
