### ISSUE TITLE
Can't seem to install on Win7 machine

### ISSUE THREAD

**Issue by talvasconcelos** [darylldoyle/Gulp-Email-Creator#68]
I keep getting a node-gyp error. I googled it and found a hack that set the path to phython.exe in system variables. 
It "installs" with npm install but when i run gulp i get an error:

Error: Cannot find module './build/Debug/htmlstrip.node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

Didn't run into this with my pinguin machine!!

**Comment by andylacko** [comment]
I have the same problem on mac node `v10.2.1`
